# Copyright 2026 Cisco Systems, Inc.
# SPDX-License-Identifier: Apache-2.0
FROM node:24.9.0-alpine3.22 AS build

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginxinc/nginx-unprivileged:1.29.1-alpine3.22
USER root
RUN apk upgrade --no-cache
USER 101
COPY nginx.production.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 8080
